spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AQE
    username: chinmay
    password: Root@123
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hariombabug123@gmail.com
    password: quizzo123
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.example: DEBUG
  file: app.log

