spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    default-property-inclusion: non_empty
  mail:
    host: smtp.gmail.com
    port: 587
    username: hariombabug123@gmail.com
    password: quizzo123
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

  datasource:
    url: jdbc:mysql://localhost:3306/AQE
    username: chinmay
    password: Root@123
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

  data.mongodb:
    host: localhost
    port: 27017
    database: AQE

#  jpa:
#    openInView: false
#    show_sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      # fixes Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
#      hibernate.jdbc.lob.non_contextual_creation: true
#
#  data:
#    jpa:
#      repositories.enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.example: DEBUG
  file: app.log

#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: all
  metrics:
    export:
      prometheus:
        enabled: true
